import { render, screen } from '@testing-library/react';
import { StorageNotices } from '../components/StorageNotices';
import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { activatePreparedVault, discardVaultSession, encryptedBackup, flushVault, prepareVault, readVaultSlot } from '../lib/vault';
import { openEncryptedVault } from '../lib/vaultCrypto';
import { decryptBackup } from '../lib/encryptedRestore';
import { exportBackupJson, exportTidyCsv } from '../lib/dataTransfer';
import { createSafeStorage, resumeWrites, storageReport } from '../store/storage';
import { STORAGE_KEY, VAULT_KEY } from '../store/keys';
import { STORE_VERSION } from '../store/migrate';
import { useStore } from '../store/useStore';
import { seedStore } from './fixtures';
const phrase='violet orchard river mountain';
beforeEach(()=>{discardVaultSession();resumeWrites();vi.stubGlobal('crypto',webcrypto);Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async (_:string,callback:()=>unknown)=>callback()}});});
afterEach(async()=>{await flushVault().catch(()=>{});discardVaultSession();resumeWrites();vi.restoreAllMocks();vi.unstubAllGlobals();});
it('keeps unsupported encrypted bytes intact, blocks writes/restore/CSV and exports the original instead of an empty snapshot',async()=>{
  seedStore('empty','kg');const {settings,doses,weights,effects}=useStore.getState();const data={settings,doses,weights,effects};
  const original=JSON.stringify({state:{...data,futureRecords:[{note:'Must survive'}]},version:STORE_VERSION+1});
  localStorage.setItem(STORAGE_KEY,original);await activatePreparedVault(await prepareVault(phrase));const encrypted=localStorage.getItem(VAULT_KEY);
  const adapter=createSafeStorage<unknown>();expect(await adapter.getItem(STORAGE_KEY)).toBeNull();expect(storageReport.unsupportedVersion).toBe(true);
  useStore.setState({readFailed:true});render(<StorageNotices/>);expect(screen.getByRole('alert')).toHaveTextContent('Download a backup preserves those original records');
  await adapter.setItem(STORAGE_KEY,{state:{},version:STORE_VERSION});await adapter.removeItem(STORAGE_KEY);await flushVault();
  expect(readVaultSlot(STORAGE_KEY)).toBe(original);expect(localStorage.getItem(VAULT_KEY)).toBe(encrypted);
  await expect(decryptBackup(await encryptedBackup(original),phrase)).rejects.toThrow(/unsupported store/);
  expect(()=>exportTidyCsv(data,'kg')).toThrow(/original JSON/);
  let blob: Blob | undefined;URL.createObjectURL=vi.fn((b:Blob)=>{blob=b;return 'blob:original';});URL.revokeObjectURL=vi.fn();vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
  await exportBackupJson(data);expect(blob).toBeDefined();const text=await new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsText(blob!);});
  const restored=await openEncryptedVault(text,phrase);expect(restored.slots[STORAGE_KEY]).toBe(original);expect(localStorage.getItem(VAULT_KEY)).toBe(encrypted);
});
